version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www
      
  node:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app
    command: 'yarn dev'
    tty: true
    ports:
      - 3000:3000

  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bs
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  
